#include <cstdio>
#include <iostream>
#include <fstream>
#include <string>

#include "./include/unroll_weights.hpp"


#include "weights.inc"

std::string FilePath = "./weights_unrolled.inc";

// constexpr std::size_t B_KP = 11*4;
// constexpr std::size_t C_KP = 12*8;
// constexpr std::size_t S_KP = 14*8;


int main(){
    std::fstream file(FilePath, std::ios::out | std::ios::trunc);
    if (!file.is_open()) {
        std::cerr << "Error opening file: " << FilePath << std::endl;
        return 1;
    }
    file << "// This file is automatically generated by unroll_weights.cpp\n";
    file << "// Do not edit this file manually. It will be overwritten.\n\n";
    file << "#pragma once\n\n";
    file << "#include <cstddef>\n";
    file << "#include <complex>\n";
    file << "#include \"./include/Matrix.hpp\"\n";
    file << "#include \"./include/MatrixOperations.hpp\"\n\n";
    file << "#include \"./include/types/Complex.hpp\"\n\n";

    WRITE_MATRICES(file, B0, 1, B_KP);

    WRITE_MATRICES(file, C0, 1, C_KP);

    WRITE_MATRICES(file, SkipLayer0_weights, 1, S_KP); // does snot exist



    file.close();
}

